version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: memoir
      POSTGRES_PASSWORD: memoir
      POSTGRES_DB: memoir
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: memoir
      RABBITMQ_DEFAULT_PASS: memoir
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
